### ISSUE TITLE
[Request] Support for Hyper

### ISSUE THREAD

**Issue by favna** [floor114/zsh-apple-touchbar#1]
Hyper is a Hyper amazing Hyper terminal.

Okay sorry I couldn't resist the pun. Jokes aside, I would love it if this plugin could get support for [Hyper](https://hyper.is) (aka Hyper Terminal but that's the name for v1.x, not v2.x)

**Comment by floor114** [comment]
Hi, @Favna. Sorry, but this plugin was written only for iTerm. So Hyper can't be supported as it has own architecture and ecosystem.

**Comment by vegerot** [comment]
Technically you can use this plugin on any Terminal (Terminal.app, iTerm, Hyper, etc.), but only the custom labels will appear in iTerm.
E.g. If you set `F1` to copy `pwd` to your clipboard with the custom label `👉 pwd`, if you run `zsh` in any terminal and press `F1` it will have the same behavior as on iTerm.  However, `👉 pwd` will not be shown instead of `F1`.

zsh-apple-touchbar is totally portable except for the custom labels
