### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by rodrigobdz** [floor114/zsh-apple-touchbar#2]
Is it possible to get this plugin to work with Fish?

**Comment by floor114** [comment]
@rodrigobdz Exactly this one - not. But I think it's possible to make such a plugin for Fish.

Set key label with:
`echo -ne "\033]1337;SetKeyLabel=F${1}=${2}\a"`
`${1}` - function key number
`${2}` - key text

And after that bind renamed key for some command:
`bindkey $keys[$1] $3`
`$keys[$1]` - key code f1, f2 and so on (`'^[OP' '^[OQ' '^[OR' '^[OS' '^[[15~' '^[[17~' '^[[18~' '^[[19~' '^[[20~' '^[[21~' '^[[23~' '^[[24~'`)
`$3` - command

You can try it in your terminal, because I don't use Fish.

**Comment by rodrigobdz** [comment]
Thanks. I will give it a try!

**Comment by floor114** [comment]
@rodrigobdz Actually you can just modify this plugin a bit, it is well-scaled.

**Comment by rodrigobdz** [comment]
@floor114 I just released [fish-apple-touchbar](https://github.com/rodrigobdz/fish-apple-touchbar). I had to adapt a significant amount of things to fish but it works! 🎉
